name: Build
on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        config: [debug, release]
        compiler: [clang, gcc, msvc, clang-cl, mingw]
        exclude:
          - os: ubuntu-latest
            compiler: msvc
          - os: ubuntu-latest
            compiler: clang-cl
          - os: ubuntu-latest
            compiler: mingw
          - os: macos-latest
            compiler: msvc
          - os: macos-latest
            compiler: clang-cl
          - os: macos-latest
            compiler: mingw
          - os: windows-latest
            compiler: clang
          - os: windows-latest
            compiler: gcc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix for actions/runner-images/issues/8659
        uses: mjp41/workaround8649@c8550b715ccdc17f89c8d5c28d7a48eeff9c94a8
        with:
          os: ${{ matrix.os }}

      - name: Configure
        run: |
          cmake --preset "${{matrix.compiler}}-${{matrix.config}}"

      - name: Unix: Build
        if: runner.os != "Windows"
        run: |
          cmake --build --preset "example-${{matrix.config}}"

      - name: Windows: Build
        if: runner.os == "Windows"
        uses: msys2/setup-msys2@v2
        shell: msys2 {0}
        run: |
          cmake --build --preset "example-${{matrix.config}}"
