name: Build
on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        config: [debug, release]
        compiler: [clang, gcc, msvc]
        exclude:
          - os: ubuntu-latest
            compiler: msvc
          - os: macos-latest
            compiler: msvc
          - os: windows-latest
            compiler: clang

          # Temporarily exluding due to GCC complaining about unknown warning
          # options (even when using GNU gcc/g++, not Apple's clang)
          - os: macos-latest
            config: debug
            compiler: gcc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix for actions/runner-images/issues/8659
        uses: mjp41/workaround8649@c8550b715ccdc17f89c8d5c28d7a48eeff9c94a8
        with:
          os: ${{ matrix.os }}

      - name: Dependencies
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          ninja: true
          cmake: true
          clangtidy: true
          cppcheck: true
          ccache: true

      # See: Line 25
      # - name: Configure (MacOS/GCC)
      #   if: ${{ matrix.os == 'macos-latest' && matrix.compiler == 'gcc' }}
      #   run: cmake --preset '${{matrix.compiler}}-${{matrix.config}}' -DCMAKE_C_COMPILER=gcc-13 -DCMAKE_CXX_COMPILER=g++-13

      - name: Configure
        # if: ${{ !(matrix.os == 'macos-latest' && matrix.compiler == 'gcc') }}
        run: cmake --preset '${{matrix.compiler}}-${{matrix.config}}'

      - name: Build
        run: cmake --build --preset 'example-${{matrix.config}}'
