name: Build
on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: 
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [clang, gcc]
        config: [debug, release]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix for actions/runner-images/issues/8659
        uses: mjp41/workaround8649@c8550b715ccdc17f89c8d5c28d7a48eeff9c94a8
        with:
          os: ${{ matrix.os }}

      - name: Configure
        run: |
          cmake --preset "${{matrix.compiler}}-${{matrix.config}}"

      - name: Build
        run: |
          cmake --build --preset "app-${{matrix.config}}"
