name: Testss
on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure
      run: |
        cmake -S . -B build
    
    - name: Build
      run: |
        cmake --build build --target test

    - name: Test
      run: |
        cd build
        ctest
